name: CI/CD Docker FastAPI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build/Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

  deploy-to-vm:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          sudo docker stop lc-fastapi-container || true
          sudo docker rm lc-fastapi-container || true
          sudo docker run -d -p 9000:9000 --name lc-fastapi-container --restart=always ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest